/* =====================================================
   Sumaq Rurucha — Datos de productos
   Fuente única de datos para catálogo y fichas de producto.
   - catalogProducts: una entrada por tarjeta del catálogo
   - productDetails: una ficha por producto (clave = slug)
   main.js construye las páginas a partir de estos objetos.
   ===================================================== */

const catalogProducts = [
  // Cereales
  { slug: "ajonjoli-tostado", category: "Cereales", title: "Ajonjolí tostado", subtext: "Cereales · Bolsa 100 g", price: "S/ 14", image: "assets/img/catalogo/Cereales/cereales-ajonjoli-tostado-100g.png", alt: "Ajonjolí tostado" },
  { slug: "ajonjoli-blanca", category: "Cereales", title: "Ajonjolí blanca", subtext: "Cereales · Bolsa 100 g", price: "S/ 12", image: "assets/img/catalogo/Cereales/cereales-ajonjoli-blanca-100g.png", alt: "Ajonjolí blanca" },
  { slug: "ajonjoli-blanca", category: "Cereales", title: "Ajonjolí blanca", subtext: "Cereales · Bolsa 1 kg", price: "S/ 38", image: "assets/img/catalogo/Cereales/cereales-Ajonjolí-blanca-1000g.png", alt: "Ajonjolí blanca 1 kg" },
  { slug: "chia-en-granos", category: "Cereales", title: "Chía en granos", subtext: "Cereales · Bolsa 500 g", price: "S/ 26", image: "assets/img/catalogo/Cereales/cereales-chia-gramos-500g.png", alt: "Chía en granos" },
  { slug: "crema-de-habas", category: "Cereales", title: "Crema de habas", subtext: "Cereales · Bolsa 100 g", price: "S/ 11", image: "assets/img/catalogo/Cereales/cereales-Crema-de-habas-100g.png", alt: "Crema de habas" },
  { slug: "harina-de-arvejas", category: "Cereales", title: "Harina de arvejas", subtext: "Cereales · Bolsa 100 g", price: "S/ 10", image: "assets/img/catalogo/Cereales/cereales-Harina-de-arvejas-100g.png", alt: "Harina de arvejas" },
  { slug: "harina-de-canihua", category: "Cereales", title: "Harina de cañihua", subtext: "Cereales · Bolsa 100 g", price: "S/ 12", image: "assets/img/catalogo/Cereales/cereales-Harina-de-cañihua-100g.png", alt: "Harina de cañihua" },
  { slug: "harina-de-quinua-tostada", category: "Cereales", title: "Harina de quinua tostada", subtext: "Cereales · Bolsa 100 g", price: "S/ 12", image: "assets/img/catalogo/Cereales/cereales-Harina-de-quinua-tostada-100g.png", alt: "Harina de quinua tostada" },
  { slug: "hojuela-de-kiwicha-organica", category: "Cereales", title: "Hojuela de kiwicha orgánica", subtext: "Cereales · Bolsa 100 g", price: "S/ 13", image: "assets/img/catalogo/Cereales/cereales-Hojuela-de-kiwicha-orgánica-100g.png", alt: "Hojuela de kiwicha orgánica" },
  { slug: "hojuela-de-kiwicha-organica", category: "Cereales", title: "Hojuela de kiwicha orgánica", subtext: "Cereales · Bolsa 1 kg", price: "S/ 38", image: "assets/img/catalogo/Cereales/cereales-Hojuela-de-kiwicha-orgánica-1000g.png", alt: "Hojuela de kiwicha orgánica 1 kg" },
  { slug: "hojuelas-de-quinua", category: "Cereales", title: "Hojuelas de quinua", subtext: "Cereales · Bolsa 100 g", price: "S/ 13", image: "assets/img/catalogo/Cereales/cereales-hojuelasdequinua-100g.png", alt: "Hojuelas de quinua" },
  { slug: "kiwicha", category: "Cereales", title: "Kiwicha", subtext: "Cereales · Bolsa 100 g", price: "S/ 12", image: "assets/img/catalogo/Cereales/cereales-kiwicha-100g.png", alt: "Kiwicha" },
  { slug: "quinua-real-blanca", category: "Cereales", title: "Quinua blanca", subtext: "Cereales · Bolsa 100 g", price: "S/ 14", image: "assets/img/catalogo/Cereales/cereales-Quinua-blanca-100g.png", alt: "Quinua blanca" },
  { slug: "quinua-real-blanca", category: "Cereales", title: "Quinua blanca", subtext: "Cereales · Bolsa 1 kg", price: "S/ 42", image: "assets/img/catalogo/Cereales/cereales -quinua-blanca-1000g.png", alt: "Quinua blanca 1 kg" },

  // Deshidratados
  { slug: "aguaymanto-fino", category: "Deshidratados", title: "Aguaymanto fino", subtext: "Deshidratados · Bolsa 100 g", price: "S/ 18", image: "assets/img/catalogo/Deshidratados/deshidratados-Aguaymanto-Fino-100g.png", alt: "Aguaymanto fino" },
  { slug: "arandanos-deshidratados", category: "Deshidratados", title: "Arándanos deshidratados", subtext: "Deshidratados · Bolsa 100 g", price: "S/ 20", image: "assets/img/catalogo/Deshidratados/deshidratados-Arándanos-deshidratados-100g.png", alt: "Arándanos deshidratados" },
  { slug: "coco-rallado-fino", category: "Deshidratados", title: "Coco rallado fino", subtext: "Deshidratados · Bolsa 100 g", price: "S/ 12", image: "assets/img/catalogo/Deshidratados/deshidratados-Coco-Rallado-Fino-100g.png", alt: "Coco rallado fino" },
  { slug: "coco-rallado-grueso", category: "Deshidratados", title: "Coco rallado grueso", subtext: "Deshidratados · Bolsa 100 g", price: "S/ 12", image: "assets/img/catalogo/Deshidratados/deshidratados-Coco-Rallado-grueso-100g.png", alt: "Coco rallado grueso" },
  { slug: "guindones", category: "Deshidratados", title: "Guindones", subtext: "Deshidratados · Bolsa 100 g", price: "S/ 16", image: "assets/img/catalogo/Deshidratados/deshidratados-Guindones-100g.png", alt: "Guindones" },
  { slug: "higo", category: "Deshidratados", title: "Higo", subtext: "Deshidratados · Bolsa 100 g", price: "S/ 15", image: "assets/img/catalogo/Deshidratados/deshidratados-Higo-100g.png", alt: "Higo" },
  { slug: "higos-secos", category: "Deshidratados", title: "Higos secos", subtext: "Deshidratados · Bolsa 100 g", price: "S/ 15", image: "assets/img/catalogo/Deshidratados/deshidratados-Higos-Secos-100g.png", alt: "Higos secos" },
  { slug: "kiwi-deshidratado", category: "Deshidratados", title: "Kiwi deshidratado", subtext: "Deshidratados · Bolsa 100 g", price: "S/ 18", image: "assets/img/catalogo/Deshidratados/Deshidratados-kiwi-100g.png", alt: "Kiwi deshidratado" },
  { slug: "pera-deshidratada", category: "Deshidratados", title: "Pera deshidratada", subtext: "Deshidratados · Bolsa 100 g", price: "S/ 17", image: "assets/img/catalogo/Deshidratados/deshidratados-Pera-deshidradata-100g.png", alt: "Pera deshidratada" },
  { slug: "toronja-deshidratada", category: "Deshidratados", title: "Toronja deshidratada", subtext: "Deshidratados · Bolsa 100 g", price: "S/ 17", image: "assets/img/catalogo/Deshidratados/deshitrados-toronja-dishidratado-100g.png", alt: "Toronja deshidratada" },

  // Especias
  { slug: "airampo", category: "Especias", title: "Airampo", subtext: "Especias · Bolsa 100 g", price: "S/ 11", image: "assets/img/catalogo/Especias/Especias-Airampo-100g.png", alt: "Airampo" },
  { slug: "aji-amarillo", category: "Especias", title: "Ají amarillo", subtext: "Especias · Bolsa 100 g", price: "S/ 13", image: "assets/img/catalogo/Especias/Especias-Aji-amarillo-100g.png", alt: "Ají amarillo" },
  { slug: "aji-panca", category: "Especias", title: "Ají panca", subtext: "Especias · Bolsa 100 g", price: "S/ 13", image: "assets/img/catalogo/Especias/Especias-Ají-panca-100g.png", alt: "Ají panca" },
  { slug: "aji-panca-molido", category: "Especias", title: "Ají panca molido", subtext: "Especias · Bolsa 100 g", price: "S/ 13", image: "assets/img/catalogo/Especias/Especias-ají-panca-molido-100g.png", alt: "Ají panca molido" },
  { slug: "anis", category: "Especias", title: "Anís", subtext: "Especias · Bolsa 100 g", price: "S/ 12", image: "assets/img/catalogo/Especias/Especias-Anís-100g.png", alt: "Anís" },
  { slug: "anis-estrella", category: "Especias", title: "Anís estrella", subtext: "Especias · Bolsa 100 g", price: "S/ 14", image: "assets/img/catalogo/Especias/Especias-Anís-estrella-100g.png", alt: "Anís estrella" },
  { slug: "bicarbonato", category: "Especias", title: "Bicarbonato", subtext: "Especias · Bolsa 100 g", price: "S/ 8", image: "assets/img/catalogo/Especias/Especias-bicarbonato-100g.png", alt: "Bicarbonato" },
  { slug: "canela-molida", category: "Especias", title: "Canela molida", subtext: "Especias · Bolsa 100 g", price: "S/ 15", image: "assets/img/catalogo/Especias/Especias-canela-molida-100g.png", alt: "Canela molida" },
  { slug: "clavo-de-olor", category: "Especias", title: "Clavo de olor", subtext: "Especias · Bolsa 100 g", price: "S/ 14", image: "assets/img/catalogo/Especias/Especias-Clavo-de-olor-100g.png", alt: "Clavo de olor" },

  // Frutos secos
  { slug: "almendras", category: "Frutos secos", title: "Almendras", subtext: "Frutos secos · Bolsa 100 g", price: "S/ 18", image: "assets/img/catalogo/Frutos secos/Fruto-secos-Almendras-100g.png", alt: "Almendras" },
  { slug: "caju-cruda", category: "Frutos secos", title: "Cajú cruda", subtext: "Frutos secos · Bolsa 100 g", price: "S/ 20", image: "assets/img/catalogo/Frutos secos/Fruto-secos-cajú-cruda-100g.png", alt: "Cajú cruda" },
  { slug: "caju-tostado", category: "Frutos secos", title: "Cajú tostado", subtext: "Frutos secos · Bolsa 100 g", price: "S/ 21", image: "assets/img/catalogo/Frutos secos/Fruto-secos-cajú-tostado-100g.png", alt: "Cajú tostado" },
  { slug: "castana", category: "Frutos secos", title: "Castaña", subtext: "Frutos secos · Bolsa 100 g", price: "S/ 22", image: "assets/img/catalogo/Frutos secos/Fruto-secos-castaña-100g.png", alt: "Castaña" },
  { slug: "mani-tostado-natural", category: "Frutos secos", title: "Maní tostado natural", subtext: "Frutos secos · Bolsa 100 g", price: "S/ 12", image: "assets/img/catalogo/Frutos secos/Fruto-secos-Maní-tostado-al-natural-100g.png", alt: "Maní tostado natural" },
  { slug: "nueces", category: "Frutos secos", title: "Nueces", subtext: "Frutos secos · Bolsa 100 g", price: "S/ 20", image: "assets/img/catalogo/Frutos secos/Fruto-secos-nueces-100g.png", alt: "Nueces" },
  { slug: "pecanas", category: "Frutos secos", title: "Pecanas", subtext: "Frutos secos · Bolsa 100 g", price: "S/ 24", image: "assets/img/catalogo/Frutos secos/Fruto-secos-Pecanas-100g.png", alt: "Pecanas" },
  { slug: "pistachos", category: "Frutos secos", title: "Pistachos", subtext: "Frutos secos · Bolsa 100 g", price: "S/ 26", image: "assets/img/catalogo/Frutos secos/Fruto-secos-pistachos-100g.png", alt: "Pistachos" },
  { slug: "sacha-inchi", category: "Frutos secos", title: "Sacha inchi", subtext: "Frutos secos · Bolsa 100 g", price: "S/ 18", image: "assets/img/catalogo/Frutos secos/Fruto-secos-sacha-inca-100g.png", alt: "Sacha inchi" },
  { slug: "pasas-morenas-importadas", category: "Frutos secos", title: "Pasas morenas importadas", subtext: "Frutos secos · Bolsa 100 g", price: "S/ 14", image: "assets/img/catalogo/Frutos secos/Fruto-secos-Pasas-morenas-importadas-grandes-100g.png", alt: "Pasas morenas importadas" },
  { slug: "pasas-morenas-nacionales", category: "Frutos secos", title: "Pasas morenas nacionales", subtext: "Frutos secos · Bolsa 100 g", price: "S/ 12", image: "assets/img/catalogo/Frutos secos/Fruto-secos-pasas-morenas-nacionales-100g.png", alt: "Pasas morenas nacionales" },
  { slug: "pasas-rubias-pequenas", category: "Frutos secos", title: "Pasas rubias pequeñas", subtext: "Frutos secos · Bolsa 100 g", price: "S/ 13", image: "assets/img/catalogo/Frutos secos/Fruto-secos-Pasas-rubias-pequeñas-100g.png", alt: "Pasas rubias pequeñas" },
  { slug: "semillas-de-calabaza", category: "Frutos secos", title: "Semillas de calabaza", subtext: "Frutos secos · Bolsa 100 g", price: "S/ 15", image: "assets/img/catalogo/Frutos secos/Fruto-secos-Semillas-de-calabaza-100g.png", alt: "Semillas de calabaza" },
  { slug: "semillas-girasol", category: "Frutos secos", title: "Semillas de girasol", subtext: "Frutos secos · Bolsa 100 g", price: "S/ 13", image: "assets/img/catalogo/Frutos secos/Fruto-secos-Semillas-de-girasol-100g.png", alt: "Semillas de girasol" },

  // Mixes para ti
  { slug: "mixes-saludables", category: "Mixes para ti", title: "Mixes saludables", subtext: "Mixes para ti · Bolsa 250 g", price: "S/ 32", image: "assets/img/catalogo/Mixes para ti/mixes-saludables.png", alt: "Mixes saludables" },
  { slug: "mixes-premium", category: "Mixes para ti", title: "Mixes premium", subtext: "Mixes para ti · Bolsa 250 g", price: "S/ 36", image: "assets/img/catalogo/Mixes para ti/Mixes-premium.png", alt: "Mixes premium" },
  { slug: "mixes-energeticos", category: "Mixes para ti", title: "Mixes energéticos", subtext: "Mixes para ti · Bolsa 250 g", price: "S/ 34", image: "assets/img/catalogo/Mixes para ti/Mixes-energéticos.png", alt: "Mixes energéticos" },
];

/* Presentaciones estándar (la mayoría de productos) */
const standardPresentations = [
  { label: "Bolsa 100 g", selected: true },
  { label: "Bolsa 250 g" },
  { label: "Bolsa 500 g" },
];

/* Fichas de producto. Campos comunes (breadcrumbs, disponibilidad,
   cantidad, galería a partir de "image") se completan en main.js. */
const productDetails = {
  // ------------------ CEREALES ------------------
  "quinua-real-blanca": {
    title: "Quinua real blanca",
    category: "Cereales",
    badge: "TOP VENTAS",
    rating: "4.9",
    reviews: "312 reseñas verificadas",
    price: "S/ 14",
    presentations: standardPresentations,
    gallery: [
      { src: "assets/img/producto/producto-quinua-blanca/producto-quinua-vista1.png", alt: "Quinua real blanca en empaque" },
      { src: "assets/img/producto/producto-quinua-blanca/producto-quinua-vista1-min.png", alt: "Vista frontal de la quinua real blanca" },
      { src: "assets/img/producto/producto-quinua-blanca/producto-quinua-detalle.png", alt: "Detalle de la quinua real blanca" },
      { src: "assets/img/producto/producto-quinua-blanca/producto-quinua-uso.png", alt: "Quinua real blanca en uso" },
    ],
    description: "Quinua real blanca cultivada en comunidades del altiplano de Puno, a más de 3,800 m s.n.m. Grano grande, de cocción rápida y sabor limpio.",
    usage: "Ideal para ensaladas, bowls, guarniciones calientes o como reemplazo de arroz.",
    facts: [
      { label: "Ingredientes", value: "100% quinua" },
      { label: "Origen", value: "Puno, Perú" },
      { label: "Cocción", value: "15 minutos" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "ajonjoli-tostado": {
    title: "Ajonjolí tostado",
    category: "Cereales",
    badge: "RECOMENDADO",
    rating: "4.7",
    reviews: "142 reseñas verificadas",
    price: "S/ 14",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Cereales/cereales-ajonjoli-tostado-100g.png",
    description: "Semillas de ajonjolí tostadas artesanalmente hasta lograr un dorado parejo y aroma intenso. Crujientes, listas para usar directo del empaque.",
    usage: "Espolvorea sobre ensaladas, panes, arroces o úsalo como base para salsas y aderezos.",
    facts: [
      { label: "Ingredientes", value: "100% ajonjolí tostado" },
      { label: "Origen", value: "Valles del norte, Perú" },
      { label: "Cocción", value: "Listo para consumo" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "ajonjoli-blanca": {
    title: "Ajonjolí blanca",
    category: "Cereales",
    badge: "CLÁSICO",
    rating: "4.6",
    reviews: "118 reseñas verificadas",
    price: "S/ 12",
    presentations: [
      { label: "Bolsa 100 g", selected: true },
      { label: "Bolsa 1 kg" },
    ],
    image: "assets/img/catalogo/Cereales/cereales-ajonjoli-blanca-100g.png",
    description: "Ajonjolí blanco crudo de grano entero y color marfil uniforme. Seleccionado y limpio, conserva todo su aceite natural y sabor suave.",
    usage: "Perfecto para tahini casero, panes, galletas o para tostar al gusto en sartén.",
    facts: [
      { label: "Ingredientes", value: "100% ajonjolí blanco" },
      { label: "Origen", value: "Valles del norte, Perú" },
      { label: "Cocción", value: "Listo para consumo" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "chia-en-granos": {
    title: "Chía en granos",
    category: "Cereales",
    badge: "TOP VENTAS",
    rating: "4.8",
    reviews: "264 reseñas verificadas",
    price: "S/ 26",
    presentations: [
      { label: "Bolsa 500 g", selected: true },
      { label: "Bolsa 100 g" },
      { label: "Bolsa 1 kg" },
    ],
    image: "assets/img/catalogo/Cereales/cereales-chia-gramos-500g.png",
    description: "Semillas de chía enteras de valles interandinos, limpias y de tamaño uniforme. Fuente natural de fibra y omega 3 de origen vegetal.",
    usage: "Remoja en agua, leche o jugo para pudines, o agrégala a batidos, yogurt y panes.",
    facts: [
      { label: "Ingredientes", value: "100% semillas de chía" },
      { label: "Origen", value: "Valles interandinos, Perú" },
      { label: "Cocción", value: "Listo para consumo" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "crema-de-habas": {
    title: "Crema de habas",
    category: "Cereales",
    badge: "CLÁSICO",
    rating: "4.6",
    reviews: "96 reseñas verificadas",
    price: "S/ 11",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Cereales/cereales-Crema-de-habas-100g.png",
    description: "Habas seleccionadas, tostadas y molidas finamente para preparar crema en minutos. Sabor casero que recuerda a la cocina de la sierra.",
    usage: "Disuelve en agua o caldo caliente y cocina 10 minutos para una crema reconfortante.",
    facts: [
      { label: "Ingredientes", value: "100% habas molidas" },
      { label: "Origen", value: "Valle del Mantaro, Junín" },
      { label: "Cocción", value: "10 minutos" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "harina-de-arvejas": {
    title: "Harina de arvejas",
    category: "Cereales",
    badge: "RECOMENDADO",
    rating: "4.5",
    reviews: "84 reseñas verificadas",
    price: "S/ 10",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Cereales/cereales-Harina-de-arvejas-100g.png",
    description: "Arvejas secas molidas en harina fina de color verde pálido. Espesa sopas y guisos de forma natural, sin aditivos.",
    usage: "Úsala para cremas, sopas, tortillas vegetales o como espesante de guisos.",
    facts: [
      { label: "Ingredientes", value: "100% arvejas molidas" },
      { label: "Origen", value: "Valle del Mantaro, Junín" },
      { label: "Cocción", value: "10 minutos" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "harina-de-canihua": {
    title: "Harina de cañihua",
    category: "Cereales",
    badge: "ORGÁNICO",
    rating: "4.7",
    reviews: "108 reseñas verificadas",
    price: "S/ 12",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Cereales/cereales-Harina-de-cañihua-100g.png",
    description: "Harina de cañihua tostada del altiplano de Puno, de aroma intenso y color canela. Un grano ancestral pequeño pero cargado de tradición.",
    usage: "Mézclala en batidos, panqueques, mazamorras o combínala con leche caliente al desayuno.",
    facts: [
      { label: "Ingredientes", value: "100% cañihua tostada y molida" },
      { label: "Origen", value: "Puno, Perú" },
      { label: "Cocción", value: "Según receta" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "harina-de-quinua-tostada": {
    title: "Harina de quinua tostada",
    category: "Cereales",
    badge: "RECOMENDADO",
    rating: "4.6",
    reviews: "132 reseñas verificadas",
    price: "S/ 12",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Cereales/cereales-Harina-de-quinua-tostada-100g.png",
    description: "Quinua tostada y molida finamente, con notas dulces y aroma a grano recién tostado. Se disuelve fácil y no forma grumos.",
    usage: "Prepara bebidas calientes, refuerza jugos y batidos o úsala en repostería.",
    facts: [
      { label: "Ingredientes", value: "100% quinua tostada y molida" },
      { label: "Origen", value: "Puno, Perú" },
      { label: "Cocción", value: "Según receta" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "hojuela-de-kiwicha-organica": {
    title: "Hojuela de kiwicha orgánica",
    category: "Cereales",
    badge: "ORGÁNICO",
    rating: "4.8",
    reviews: "176 reseñas verificadas",
    price: "S/ 13",
    presentations: [
      { label: "Bolsa 100 g", selected: true },
      { label: "Bolsa 1 kg" },
    ],
    image: "assets/img/catalogo/Cereales/cereales-Hojuela-de-kiwicha-orgánica-100g.png",
    description: "Hojuelas ligeras de kiwicha de cultivo orgánico, laminadas para cocción rápida. Sabor suave que gusta a grandes y niños.",
    usage: "Cocina 3-5 minutos con leche o agua para un porridge, o agrégalas a yogurt y jugos.",
    facts: [
      { label: "Ingredientes", value: "100% kiwicha orgánica" },
      { label: "Origen", value: "Valles interandinos, Perú" },
      { label: "Cocción", value: "3-5 minutos" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "hojuelas-de-quinua": {
    title: "Hojuelas de quinua",
    category: "Cereales",
    badge: "TOP VENTAS",
    rating: "4.7",
    reviews: "204 reseñas verificadas",
    price: "S/ 13",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Cereales/cereales-hojuelasdequinua-100g.png",
    description: "Quinua laminada en hojuelas finas que se cocinan en minutos. La alternativa andina a la avena, con grano de Puno.",
    usage: "Ideal para porridge, mazamorras, galletas caseras o para espesar jugos de desayuno.",
    facts: [
      { label: "Ingredientes", value: "100% quinua laminada" },
      { label: "Origen", value: "Puno, Perú" },
      { label: "Cocción", value: "3-5 minutos" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "kiwicha": {
    title: "Kiwicha",
    category: "Cereales",
    badge: "CLÁSICO",
    rating: "4.6",
    reviews: "124 reseñas verificadas",
    price: "S/ 12",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Cereales/cereales-kiwicha-100g.png",
    description: "Grano entero de kiwicha, diminuto y de color crema, cultivado en valles interandinos. Un alimento ancestral que acompañó a los Andes por siglos.",
    usage: "Cocínala como guarnición, ináflala para turrones y barras, o súmala a sopas.",
    facts: [
      { label: "Ingredientes", value: "100% kiwicha" },
      { label: "Origen", value: "Valles interandinos, Perú" },
      { label: "Cocción", value: "10 minutos" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },

  // ------------------ DESHIDRATADOS ------------------
  "aguaymanto-fino": {
    title: "Aguaymanto fino",
    category: "Deshidratados",
    badge: "TOP VENTAS",
    rating: "4.8",
    reviews: "188 reseñas verificadas",
    price: "S/ 18",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Deshidratados/deshidratados-Aguaymanto-Fino-100g.png",
    description: "Aguaymanto de Cajamarca deshidratado a baja temperatura para conservar su color naranja intenso y su equilibrio dulce-ácido característico.",
    usage: "Cómelo como snack, o úsalo en ensaladas, granolas, chocolates y postres.",
    facts: [
      { label: "Ingredientes", value: "100% aguaymanto" },
      { label: "Origen", value: "Cajamarca, Perú" },
      { label: "Cocción", value: "Listo para consumo" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "arandanos-deshidratados": {
    title: "Arándanos deshidratados",
    category: "Deshidratados",
    badge: "RECOMENDADO",
    rating: "4.7",
    reviews: "156 reseñas verificadas",
    price: "S/ 20",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Deshidratados/deshidratados-Arándanos-deshidratados-100g.png",
    description: "Arándanos de La Libertad deshidratados enteros, carnosos y de dulzor concentrado. Sin colorantes ni saborizantes.",
    usage: "Agrégalos a yogurt, avena, ensaladas o disfrútalos directo como snack.",
    facts: [
      { label: "Ingredientes", value: "100% arándanos" },
      { label: "Origen", value: "La Libertad, Perú" },
      { label: "Cocción", value: "Listo para consumo" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "coco-rallado-fino": {
    title: "Coco rallado fino",
    category: "Deshidratados",
    badge: "TOP VENTAS",
    rating: "4.8",
    reviews: "207 reseñas verificadas",
    price: "S/ 12",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Deshidratados/deshidratados-Coco-Rallado-Fino-100g.png",
    description: "Coco rallado en hebra fina, deshidratado y sin azúcar añadida. Textura ligera que se integra fácil en cualquier preparación dulce.",
    usage: "Ideal para pasteles, granolas, trufas y preparaciones de desayuno.",
    facts: [
      { label: "Ingredientes", value: "100% coco rallado" },
      { label: "Origen", value: "Selva peruana" },
      { label: "Cocción", value: "Listo para consumo" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "coco-rallado-grueso": {
    title: "Coco rallado grueso",
    category: "Deshidratados",
    badge: "RECOMENDADO",
    rating: "4.6",
    reviews: "112 reseñas verificadas",
    price: "S/ 12",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Deshidratados/deshidratados-Coco-Rallado-grueso-100g.png",
    description: "Hojuelas gruesas de coco deshidratado que conservan más textura y crocancia. Perfectas cuando quieres que el coco se sienta.",
    usage: "Úsalo para rebozar trufas, decorar tortas, o tostar y sumar a bowls y granolas.",
    facts: [
      { label: "Ingredientes", value: "100% coco rallado" },
      { label: "Origen", value: "Selva peruana" },
      { label: "Cocción", value: "Listo para consumo" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "guindones": {
    title: "Guindones",
    category: "Deshidratados",
    badge: "CLÁSICO",
    rating: "4.6",
    reviews: "134 reseñas verificadas",
    price: "S/ 16",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Deshidratados/deshidratados-Guindones-100g.png",
    description: "Guindones carnosos y oscuros, seleccionados por tamaño y suavidad. Dulzor natural concentrado, sin azúcar añadida.",
    usage: "Perfectos para compotas, mazamorras, guisos dulces o como snack digestivo.",
    facts: [
      { label: "Ingredientes", value: "100% ciruelas deshidratadas" },
      { label: "Origen", value: "Selección importada" },
      { label: "Cocción", value: "Listo para consumo" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "higo": {
    title: "Higo",
    category: "Deshidratados",
    badge: "RECOMENDADO",
    rating: "4.5",
    reviews: "92 reseñas verificadas",
    price: "S/ 15",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Deshidratados/deshidratados-Higo-100g.png",
    description: "Higos deshidratados enteros de valles de Ica, suaves por dentro y de dulzor intenso. Fruta con historia en la despensa peruana.",
    usage: "Acompaña tablas de quesos, postres, o pícalos en ensaladas y panes caseros.",
    facts: [
      { label: "Ingredientes", value: "100% higo" },
      { label: "Origen", value: "Ica, Perú" },
      { label: "Cocción", value: "Listo para consumo" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "higos-secos": {
    title: "Higos secos",
    category: "Deshidratados",
    badge: "CLÁSICO",
    rating: "4.6",
    reviews: "104 reseñas verificadas",
    price: "S/ 15",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Deshidratados/deshidratados-Higos-Secos-100g.png",
    description: "Higos secos tradicionales de secado prolongado, con interior rojizo lleno de semillas crocantes y dulzor profundo tipo miel.",
    usage: "Ideales con queso fresco y miel, en repostería o remojados para postres.",
    facts: [
      { label: "Ingredientes", value: "100% higos secos" },
      { label: "Origen", value: "Ica, Perú" },
      { label: "Cocción", value: "Listo para consumo" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "kiwi-deshidratado": {
    title: "Kiwi deshidratado",
    category: "Deshidratados",
    badge: "NUEVO",
    rating: "4.7",
    reviews: "86 reseñas verificadas",
    price: "S/ 18",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Deshidratados/Deshidratados-kiwi-100g.png",
    description: "Rodajas de kiwi deshidratado de color verde translúcido y sabor dulce-ácido refrescante. Un snack diferente y lleno de color.",
    usage: "Cómelo directo, agrégalo a mixes y granolas o úsalo para infusionar agua.",
    facts: [
      { label: "Ingredientes", value: "100% kiwi" },
      { label: "Origen", value: "Selección importada" },
      { label: "Cocción", value: "Listo para consumo" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "pera-deshidratada": {
    title: "Pera deshidratada",
    category: "Deshidratados",
    badge: "NUEVO",
    rating: "4.6",
    reviews: "88 reseñas verificadas",
    price: "S/ 17",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Deshidratados/deshidratados-Pera-deshidradata-100g.png",
    description: "Láminas de pera deshidratada de dulzor delicado y textura suave. Conserva el aroma de la fruta madura sin azúcar añadida.",
    usage: "Suma a tu avena, tés y ensaladas, o disfrútala directa como snack ligero.",
    facts: [
      { label: "Ingredientes", value: "100% pera" },
      { label: "Origen", value: "Valles interandinos, Perú" },
      { label: "Cocción", value: "Listo para consumo" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "toronja-deshidratada": {
    title: "Toronja deshidratada",
    category: "Deshidratados",
    badge: "NUEVO",
    rating: "4.5",
    reviews: "80 reseñas verificadas",
    price: "S/ 17",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Deshidratados/deshitrados-toronja-dishidratado-100g.png",
    description: "Rodajas de toronja deshidratada con notas cítricas y un toque amargo elegante. Tan vistosa como sabrosa.",
    usage: "Perfecta para decorar bebidas, tés helados y postres, o como snack cítrico.",
    facts: [
      { label: "Ingredientes", value: "100% toronja" },
      { label: "Origen", value: "Selva central, Perú" },
      { label: "Cocción", value: "Listo para consumo" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },

  // ------------------ ESPECIAS ------------------
  "airampo": {
    title: "Airampo",
    category: "Especias",
    badge: "CLÁSICO",
    rating: "4.6",
    reviews: "94 reseñas verificadas",
    price: "S/ 11",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Especias/Especias-Airampo-100g.png",
    description: "Semillas de airampo de los Andes del sur, usadas por generaciones para dar color carmín natural a refrescos y postres tradicionales.",
    usage: "Hierve o remoja las semillas para teñir mazamorras, chicha y refrescos.",
    facts: [
      { label: "Ingredientes", value: "100% semillas de airampo" },
      { label: "Origen", value: "Cusco y Ayacucho, Perú" },
      { label: "Cocción", value: "Infusión 5 minutos" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "aji-amarillo": {
    title: "Ají amarillo",
    category: "Especias",
    badge: "TOP VENTAS",
    rating: "4.8",
    reviews: "216 reseñas verificadas",
    price: "S/ 13",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Especias/Especias-Aji-amarillo-100g.png",
    description: "Ají amarillo seco, el alma de la cocina peruana. Aporta color dorado, picor medio y ese sabor inconfundible de casa.",
    usage: "Hidrátalo y licúalo para causa, ají de gallina, huancaína y salsas criollas.",
    facts: [
      { label: "Ingredientes", value: "100% ají amarillo seco" },
      { label: "Origen", value: "Costa peruana" },
      { label: "Cocción", value: "Según receta" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "aji-panca": {
    title: "Ají panca",
    category: "Especias",
    badge: "CLÁSICO",
    rating: "4.7",
    reviews: "168 reseñas verificadas",
    price: "S/ 13",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Especias/Especias-Ají-panca-100g.png",
    description: "Ají panca seco entero, de color rojo profundo y sabor ahumado sin picor agresivo. Base de los adobos y anticuchos peruanos.",
    usage: "Remoja, despepita y licúa para adobos, anticuchos, carapulcra y guisos.",
    facts: [
      { label: "Ingredientes", value: "100% ají panca seco" },
      { label: "Origen", value: "Costa peruana" },
      { label: "Cocción", value: "Según receta" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "aji-panca-molido": {
    title: "Ají panca molido",
    category: "Especias",
    badge: "RECOMENDADO",
    rating: "4.7",
    reviews: "144 reseñas verificadas",
    price: "S/ 13",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Especias/Especias-ají-panca-molido-100g.png",
    description: "Ají panca molido listo para usar, color rojo ladrillo y aroma ahumado. Todo el sabor del panca sin el trabajo de remojarlo.",
    usage: "Agrega una cucharada directa a aderezos, guisos, marinadas y salsas.",
    facts: [
      { label: "Ingredientes", value: "100% ají panca molido" },
      { label: "Origen", value: "Costa peruana" },
      { label: "Cocción", value: "Según receta" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "anis": {
    title: "Anís",
    category: "Especias",
    badge: "CLÁSICO",
    rating: "4.7",
    reviews: "152 reseñas verificadas",
    price: "S/ 12",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Especias/Especias-Anís-100g.png",
    description: "Anís de Curahuasi, Apurímac, reconocido entre los mejores del mundo por su aroma dulce e intenso. Semilla entera seleccionada.",
    usage: "Prepara infusiones digestivas o úsalo en panes, mazamorras y postres.",
    facts: [
      { label: "Ingredientes", value: "100% anís en semilla" },
      { label: "Origen", value: "Curahuasi, Apurímac" },
      { label: "Cocción", value: "Infusión 5 minutos" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "anis-estrella": {
    title: "Anís estrella",
    category: "Especias",
    badge: "TOP VENTAS",
    rating: "4.8",
    reviews: "184 reseñas verificadas",
    price: "S/ 14",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Especias/Especias-Anís-estrella-100g.png",
    description: "Especia aromática de sabor intenso, ideal para infusiones, postres y mezclas especiadas.",
    usage: "Perfecto para infusiones, repostería y preparaciones aromáticas.",
    facts: [
      { label: "Ingredientes", value: "100% anís estrella" },
      { label: "Origen", value: "Selección importada" },
      { label: "Cocción", value: "Infusión 5 minutos" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "bicarbonato": {
    title: "Bicarbonato",
    category: "Especias",
    badge: "CLÁSICO",
    rating: "4.6",
    reviews: "110 reseñas verificadas",
    price: "S/ 8",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Especias/Especias-bicarbonato-100g.png",
    description: "Bicarbonato de sodio puro de grado alimentario, polvo fino y sin aditivos. Un básico multiuso de la despensa.",
    usage: "Úsalo en repostería para masas esponjosas o para remojar y ablandar legumbres.",
    facts: [
      { label: "Ingredientes", value: "100% bicarbonato de sodio" },
      { label: "Origen", value: "Grado alimentario, Perú" },
      { label: "Cocción", value: "Según receta" },
      { label: "Conservación", value: "Lugar seco y cerrado" },
    ],
  },
  "canela-molida": {
    title: "Canela molida",
    category: "Especias",
    badge: "TOP VENTAS",
    rating: "4.8",
    reviews: "232 reseñas verificadas",
    price: "S/ 15",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Especias/Especias-canela-molida-100g.png",
    description: "Canela molida de aroma dulce y cálido, molienda fina que se disuelve sin dejar residuos. Seleccionada por su intensidad.",
    usage: "Espolvorea en bebidas calientes, avenas y postres, o úsala en adobos dulces.",
    facts: [
      { label: "Ingredientes", value: "100% canela molida" },
      { label: "Origen", value: "Selección importada" },
      { label: "Cocción", value: "Según receta" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "clavo-de-olor": {
    title: "Clavo de olor",
    category: "Especias",
    badge: "CLÁSICO",
    rating: "4.6",
    reviews: "98 reseñas verificadas",
    price: "S/ 14",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Especias/Especias-Clavo-de-olor-100g.png",
    description: "Clavo de olor entero de aroma profundo y especiado. Pocas unidades bastan para perfumar toda una preparación.",
    usage: "Aromatiza mazamorras, arroz con leche, vino caliente y guisos de sabor intenso.",
    facts: [
      { label: "Ingredientes", value: "100% clavo de olor" },
      { label: "Origen", value: "Selección importada" },
      { label: "Cocción", value: "Según receta" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },

  // ------------------ FRUTOS SECOS ------------------
  "almendras": {
    title: "Almendras",
    category: "Frutos secos",
    badge: "TOP VENTAS",
    rating: "4.8",
    reviews: "246 reseñas verificadas",
    price: "S/ 18",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Frutos secos/Fruto-secos-Almendras-100g.png",
    description: "Almendras enteras crudas de primera selección, uniformes y crocantes. Sin sal ni aceites añadidos.",
    usage: "Snack directo, leche de almendras casera, o tuéstalas para ensaladas y postres.",
    facts: [
      { label: "Ingredientes", value: "100% almendras" },
      { label: "Origen", value: "Selección importada" },
      { label: "Cocción", value: "Listo para consumo" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "caju-cruda": {
    title: "Cajú cruda",
    category: "Frutos secos",
    badge: "RECOMENDADO",
    rating: "4.7",
    reviews: "138 reseñas verificadas",
    price: "S/ 20",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Frutos secos/Fruto-secos-cajú-cruda-100g.png",
    description: "Castañas de cajú crudas, enteras y de color marfil. Textura mantequillosa ideal para preparaciones cremosas.",
    usage: "Remoja y licúa para cremas y quesos veganos, o tuéstalas al gusto.",
    facts: [
      { label: "Ingredientes", value: "100% cajú crudo" },
      { label: "Origen", value: "Selección importada" },
      { label: "Cocción", value: "Listo para consumo" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "caju-tostado": {
    title: "Cajú tostado",
    category: "Frutos secos",
    badge: "TOP VENTAS",
    rating: "4.8",
    reviews: "192 reseñas verificadas",
    price: "S/ 21",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Frutos secos/Fruto-secos-cajú-tostado-100g.png",
    description: "Castañas de cajú tostadas al punto dorado exacto, crocantes por fuera y suaves al morder. Sin sal añadida.",
    usage: "Snack listo para comer, o agrégalo a salteados, arroces y ensaladas.",
    facts: [
      { label: "Ingredientes", value: "100% cajú tostado" },
      { label: "Origen", value: "Selección importada" },
      { label: "Cocción", value: "Listo para consumo" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "castana": {
    title: "Castaña",
    category: "Frutos secos",
    badge: "ORGÁNICO",
    rating: "4.7",
    reviews: "146 reseñas verificadas",
    price: "S/ 22",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Frutos secos/Fruto-secos-castaña-100g.png",
    description: "Castaña amazónica de Madre de Dios, recolectada de bosques naturales. Grande, cremosa y de sabor delicado.",
    usage: "Cómela directa, pícala en postres o combínala con chocolate y frutas secas.",
    facts: [
      { label: "Ingredientes", value: "100% castaña amazónica" },
      { label: "Origen", value: "Madre de Dios, Perú" },
      { label: "Cocción", value: "Listo para consumo" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "mani-tostado-natural": {
    title: "Maní tostado al natural",
    category: "Frutos secos",
    badge: "TOP VENTAS",
    rating: "4.9",
    reviews: "256 reseñas verificadas",
    price: "S/ 12",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Frutos secos/Fruto-secos-Maní-tostado-al-natural-100g.png",
    description: "Snack clásico, tostado sin añadidos, ideal para consumo directo o mixes.",
    usage: "Perfecto para meriendas, mezclas y consumo directo.",
    facts: [
      { label: "Ingredientes", value: "100% maní tostado" },
      { label: "Origen", value: "Perú" },
      { label: "Cocción", value: "Listo para consumo" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "nueces": {
    title: "Nueces",
    category: "Frutos secos",
    badge: "RECOMENDADO",
    rating: "4.7",
    reviews: "164 reseñas verificadas",
    price: "S/ 20",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Frutos secos/Fruto-secos-nueces-100g.png",
    description: "Nueces peladas en mitades, frescas y de color dorado claro. Seleccionadas para que lleguen enteras, no en trozos.",
    usage: "Ideales en brownies, ensaladas, panes o como snack con fruta.",
    facts: [
      { label: "Ingredientes", value: "100% nueces peladas" },
      { label: "Origen", value: "Selección importada" },
      { label: "Cocción", value: "Listo para consumo" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "pecanas": {
    title: "Pecanas",
    category: "Frutos secos",
    badge: "TOP VENTAS",
    rating: "4.8",
    reviews: "212 reseñas verificadas",
    price: "S/ 24",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Frutos secos/Fruto-secos-Pecanas-100g.png",
    description: "Pecanas de Ica en mitades, dulces y mantequillosas. El valle pecanero del Perú en su mejor expresión.",
    usage: "Perfectas para tartas, queques, ensaladas dulces o directo como snack.",
    facts: [
      { label: "Ingredientes", value: "100% pecanas" },
      { label: "Origen", value: "Ica, Perú" },
      { label: "Cocción", value: "Listo para consumo" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "pistachos": {
    title: "Pistachos",
    category: "Frutos secos",
    badge: "NUEVO",
    rating: "4.7",
    reviews: "128 reseñas verificadas",
    price: "S/ 26",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Frutos secos/Fruto-secos-pistachos-100g.png",
    description: "Pistachos tostados con cáscara entreabierta, de grano verde y sabor delicado. Selección premium de calibre grande.",
    usage: "Snack elegante, o pélalos para helados, postres y costras de carnes.",
    facts: [
      { label: "Ingredientes", value: "100% pistachos" },
      { label: "Origen", value: "Selección importada" },
      { label: "Cocción", value: "Listo para consumo" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "sacha-inchi": {
    title: "Sacha inchi",
    category: "Frutos secos",
    badge: "ORGÁNICO",
    rating: "4.7",
    reviews: "150 reseñas verificadas",
    price: "S/ 18",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Frutos secos/Fruto-secos-sacha-inca-100g.png",
    description: "Semillas de sacha inchi de la Amazonía de San Martín, tostadas para lograr crocancia y sabor a nuez. El 'maní del inca', rico en omega 3.",
    usage: "Snack directo entre comidas, o agrégalo a ensaladas, yogurt y mixes.",
    facts: [
      { label: "Ingredientes", value: "100% sacha inchi tostado" },
      { label: "Origen", value: "San Martín, Perú" },
      { label: "Cocción", value: "Listo para consumo" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "pasas-morenas-importadas": {
    title: "Pasas morenas importadas",
    category: "Frutos secos",
    badge: "RECOMENDADO",
    rating: "4.6",
    reviews: "120 reseñas verificadas",
    price: "S/ 14",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Frutos secos/Fruto-secos-Pasas-morenas-importadas-grandes-100g.png",
    description: "Pasas morenas de calibre grande, carnosas y jugosas. Seleccionadas por tamaño para que luzcan en cualquier preparación.",
    usage: "Ideales para arroz árabe, panetón casero, guisos dulces y repostería.",
    facts: [
      { label: "Ingredientes", value: "100% pasas morenas" },
      { label: "Origen", value: "Selección importada" },
      { label: "Cocción", value: "Listo para consumo" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "pasas-morenas-nacionales": {
    title: "Pasas morenas nacionales",
    category: "Frutos secos",
    badge: "CLÁSICO",
    rating: "4.6",
    reviews: "106 reseñas verificadas",
    price: "S/ 12",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Frutos secos/Fruto-secos-pasas-morenas-nacionales-100g.png",
    description: "Pasas morenas de uva peruana de Ica, de dulzor concentrado y textura suave. Apoyo directo a la producción nacional.",
    usage: "Perfectas para postres criollos, mazamorras, panes y snacks de media tarde.",
    facts: [
      { label: "Ingredientes", value: "100% pasas de uva" },
      { label: "Origen", value: "Ica, Perú" },
      { label: "Cocción", value: "Listo para consumo" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "pasas-rubias-pequenas": {
    title: "Pasas rubias pequeñas",
    category: "Frutos secos",
    badge: "RECOMENDADO",
    rating: "4.5",
    reviews: "90 reseñas verificadas",
    price: "S/ 13",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Frutos secos/Fruto-secos-Pasas-rubias-pequeñas-100g.png",
    description: "Pasas rubias pequeñas de color ámbar dorado y dulzor delicado. Su tamaño las hace perfectas para repartirse parejo en masas.",
    usage: "Úsalas en ensaladas, cuscús, panes dulces y mezclas de frutos secos.",
    facts: [
      { label: "Ingredientes", value: "100% pasas rubias" },
      { label: "Origen", value: "Selección importada" },
      { label: "Cocción", value: "Listo para consumo" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "semillas-de-calabaza": {
    title: "Semillas de calabaza",
    category: "Frutos secos",
    badge: "RECOMENDADO",
    rating: "4.7",
    reviews: "134 reseñas verificadas",
    price: "S/ 15",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Frutos secos/Fruto-secos-Semillas-de-calabaza-100g.png",
    description: "Semillas de calabaza peladas, de color verde oliva intenso. Crocantes y versátiles, sin sal ni aceites.",
    usage: "Tuéstalas para sopas y ensaladas, o agrégalas a granolas y panes.",
    facts: [
      { label: "Ingredientes", value: "100% semillas de calabaza" },
      { label: "Origen", value: "Valles costeros, Perú" },
      { label: "Cocción", value: "Listo para consumo" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "semillas-girasol": {
    title: "Semillas de girasol",
    category: "Frutos secos",
    badge: "NUEVO",
    rating: "4.7",
    reviews: "129 reseñas verificadas",
    price: "S/ 13",
    presentations: standardPresentations,
    image: "assets/img/catalogo/Frutos secos/Fruto-secos-Semillas-de-girasol-100g.png",
    description: "Semillas naturales listas para snacks, desayunos y mezclas caseras.",
    usage: "Úsalas en ensaladas, panes, bowls o como snack directo.",
    facts: [
      { label: "Ingredientes", value: "100% semillas de girasol" },
      { label: "Origen", value: "Perú" },
      { label: "Cocción", value: "Listo para consumo" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },

  // ------------------ MIXES PARA TI ------------------
  "mixes-saludables": {
    title: "Mixes saludables",
    category: "Mixes para ti",
    badge: "RECOMENDADO",
    rating: "4.7",
    reviews: "158 reseñas verificadas",
    price: "S/ 32",
    presentations: [
      { label: "Bolsa 250 g", selected: true },
      { label: "Bolsa 500 g" },
    ],
    image: "assets/img/catalogo/Mixes para ti/mixes-saludables.png",
    description: "Mezcla equilibrada de frutos secos, semillas y frutas deshidratadas, pensada para el día a día. Sin sal, sin azúcar añadida y sin frituras.",
    usage: "Llévalo al trabajo, al gimnasio o de viaje: una porción rinde para media mañana.",
    facts: [
      { label: "Ingredientes", value: "Frutos secos, semillas y frutas deshidratadas" },
      { label: "Origen", value: "Elaborado en Perú" },
      { label: "Cocción", value: "Listo para consumo" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "mixes-premium": {
    title: "Mixes premium",
    category: "Mixes para ti",
    badge: "TOP VENTAS",
    rating: "4.8",
    reviews: "186 reseñas verificadas",
    price: "S/ 36",
    presentations: [
      { label: "Bolsa 250 g", selected: true },
      { label: "Bolsa 500 g" },
    ],
    image: "assets/img/catalogo/Mixes para ti/Mixes-premium.png",
    description: "Nuestra selección más fina: nueces, pecanas, castañas amazónicas, arándanos y aguaymanto. Solo ingredientes de primera, en proporciones generosas.",
    usage: "Perfecto para tablas de picoteo, regalos y ocasiones que merecen algo especial.",
    facts: [
      { label: "Ingredientes", value: "Nueces, pecanas, castañas, arándanos y aguaymanto" },
      { label: "Origen", value: "Elaborado en Perú" },
      { label: "Cocción", value: "Listo para consumo" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "mixes-energeticos": {
    title: "Mixes energéticos",
    category: "Mixes para ti",
    badge: "NUEVO",
    rating: "4.7",
    reviews: "140 reseñas verificadas",
    price: "S/ 34",
    presentations: [
      { label: "Bolsa 250 g", selected: true },
      { label: "Bolsa 500 g" },
    ],
    image: "assets/img/catalogo/Mixes para ti/Mixes-energéticos.png",
    description: "Combinación pensada para rendir: maní, cajú, pasas y trozos de chocolate. Energía rápida y sostenida para entrenamientos y caminatas.",
    usage: "Ideal antes o después del ejercicio, en trekkings o jornadas largas de estudio.",
    facts: [
      { label: "Ingredientes", value: "Maní, cajú, pasas y chocolate" },
      { label: "Origen", value: "Elaborado en Perú" },
      { label: "Cocción", value: "Listo para consumo" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },

  // ------------------ PRODUCTOS DEL HOME ------------------
  "mango-deshidratado": {
    title: "Mango deshidratado",
    category: "Deshidratados",
    badge: "TOP VENTAS",
    rating: "4.8",
    reviews: "198 reseñas verificadas",
    price: "S/ 18",
    presentations: [
      { label: "Pack 250 g", selected: true },
      { label: "Bolsa 100 g" },
    ],
    gallery: [
      { src: "assets/img/producto/producto-mango-deshidratado/producto-mango-vista1.png", alt: "Mango deshidratado en empaque" },
      { src: "assets/img/producto/producto-mango-deshidratado/producto-mango-vista2.png", alt: "Vista alternativa del mango deshidratado" },
      { src: "assets/img/producto/producto-mango-deshidratado/producto-mango-detalle.png", alt: "Detalle de las tiras de mango deshidratado" },
      { src: "assets/img/producto/producto-mango-deshidratado/producto-mango-uso.png", alt: "Mango deshidratado en uso" },
    ],
    description: "Tiras de mango de Piura deshidratadas a baja temperatura, sin azúcar añadida. Dulzor natural intenso y textura suave que no empalaga.",
    usage: "Snack directo, o pícalo en yogurt, granolas, ensaladas y postres tropicales.",
    facts: [
      { label: "Ingredientes", value: "100% mango" },
      { label: "Origen", value: "Piura, Perú" },
      { label: "Cocción", value: "Listo para consumo" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "curcuma-molida": {
    title: "Cúrcuma molida",
    category: "Especias",
    badge: "RECOMENDADO",
    rating: "4.7",
    reviews: "162 reseñas verificadas",
    price: "S/ 15",
    presentations: [
      { label: "Frasco 120 g", selected: true },
      { label: "Bolsa 100 g" },
    ],
    gallery: [
      { src: "assets/img/producto/producto-curcuma-molida/producto-curcuma-vista1.png", alt: "Cúrcuma molida en empaque" },
      { src: "assets/img/producto/producto-curcuma-molida/producto-curcuma-vista2.png", alt: "Vista alternativa de la cúrcuma molida" },
      { src: "assets/img/producto/producto-curcuma-molida/producto-curcuma-detalle.png", alt: "Detalle del polvo de cúrcuma" },
      { src: "assets/img/producto/producto-curcuma-molida/producto-curcuma-uso.png", alt: "Cúrcuma molida en uso" },
    ],
    description: "Cúrcuma de la selva central molida finamente, de color naranja dorado intenso y aroma terroso. Molienda fresca en lotes pequeños.",
    usage: "Úsala en golden milk, arroces, guisos y aderezos; combina bien con pimienta.",
    facts: [
      { label: "Ingredientes", value: "100% cúrcuma molida" },
      { label: "Origen", value: "Junín, Perú" },
      { label: "Cocción", value: "Según receta" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "mix-andino-premium": {
    title: "Mix andino premium",
    category: "Mixes para ti",
    badge: "TOP VENTAS",
    rating: "4.8",
    reviews: "174 reseñas verificadas",
    price: "S/ 32",
    presentations: [
      { label: "Bolsa 500 g", selected: true },
      { label: "Bolsa 250 g" },
    ],
    gallery: [
      { src: "assets/img/producto/producto-mix-andino-premium/producto-mix-vista1.png", alt: "Mix andino premium en empaque" },
      { src: "assets/img/producto/producto-mix-andino-premium/producto-mix-vista2.png", alt: "Vista alternativa del mix andino premium" },
      { src: "assets/img/producto/producto-mix-andino-premium/producto-mix-detalle.png", alt: "Detalle de los frutos secos del mix andino" },
      { src: "assets/img/producto/producto-mix-andino-premium/producto-mix-uso.png", alt: "Mix andino premium en uso" },
    ],
    description: "Mezcla insignia de la casa: frutos secos seleccionados con frutas andinas deshidratadas. Cada bolsa combina origen, textura y sabor.",
    usage: "Disfrútalo como snack diario o llévalo de viaje: energía natural en cada puñado.",
    facts: [
      { label: "Ingredientes", value: "Frutos secos y frutas andinas deshidratadas" },
      { label: "Origen", value: "Elaborado en Perú" },
      { label: "Cocción", value: "Listo para consumo" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
  "infusion-natural": {
    title: "Infusión natural",
    category: "Especias",
    badge: "NUEVO",
    rating: "4.7",
    reviews: "116 reseñas verificadas",
    price: "S/ 18",
    presentations: [
      { label: "Bolsa 50 g", selected: true },
      { label: "Bolsa 100 g" },
    ],
    gallery: [
      { src: "assets/img/producto/producto-infusion-natural/producto-infusion-vista1.png", alt: "Infusión natural en empaque" },
      { src: "assets/img/producto/producto-infusion-natural/producto-infusion-vista2.png", alt: "Vista alternativa de la infusión natural" },
      { src: "assets/img/producto/producto-infusion-natural/producto-infusion-detalle.png", alt: "Detalle de las hierbas de la infusión" },
      { src: "assets/img/producto/producto-infusion-natural/producto-infusion-uso.png", alt: "Infusión natural servida en taza" },
    ],
    description: "Mezcla de hierbas andinas secas —muña, manzanilla y anís— para una infusión digestiva y aromática. Hojas y flores enteras, no polvo.",
    usage: "Infusiona una cucharada en agua caliente por 3-5 minutos; ideal después de las comidas.",
    facts: [
      { label: "Ingredientes", value: "Muña, manzanilla y anís" },
      { label: "Origen", value: "Hierbas andinas, Perú" },
      { label: "Cocción", value: "Infusión 3-5 minutos" },
      { label: "Conservación", value: "Lugar fresco y seco" },
    ],
  },
};
